import JSZip from "https://cdn.jsdelivr.net/npm/jszip@3.10.1/+esm";
import { buildEngineProfiles, deriveCameraFromCapture, enrichCaptureJson, round } from "./math.js";

export function extensionFromMime(mime) {
  if (mime === "image/png") return "png";
  if (mime === "image/webp") return "webp";
  return "jpg";
}

export function safeFileName(name) {
  return String(name || "capture")
    .trim()
    .replace(/[^a-zA-Z0-9._-]+/g, "_")
    .replace(/^_+|_+$/g, "") || "capture";
}

export function downloadBlob(blob, fileName) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 30000);
}

export async function blobToDataUrl(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(blob);
  });
}

export function jsonBlob(json) {
  return new Blob([JSON.stringify(json, null, 2)], { type: "application/json" });
}

export function textBlob(text, type = "text/plain") {
  return new Blob([text], { type });
}

export function makeJsonForExport(record) {
  return enrichCaptureJson(record.json);
}

export function generateEngineSnippet(record, engine = "generic") {
  const json = makeJsonForExport(record);
  const profiles = buildEngineProfiles(json);
  const profile = profiles[engine] || profiles.generic;

  if (engine === "unity") return unitySnippet(json, profiles.unity);
  if (engine === "unreal") return JSON.stringify(profiles.unreal, null, 2);
  if (engine === "blender") return blenderSnippet(json, profiles.blender);
  if (engine === "three") return threeSnippet(json, profiles.three);
  if (engine === "godot") return godotSnippet(json, profiles.godot);
  if (engine === "gltf") return JSON.stringify(profiles.gltf, null, 2);
  return JSON.stringify(profile, null, 2);
}

function headerComment(json, title) {
  return [
    `// ${title}`,
    `// Capture id: ${json.id}`,
    `// Plate image: ${json.image?.fileName || "unknown"}`,
    "// Generated by Phone Scene Calibrator. Values marked estimated should be calibrated in-engine."
  ].join("\n");
}

function unitySnippet(json, p) {
  const masks = JSON.stringify(json.scene?.occluders || [], null, 2).replaceAll("*/", "* /");
  return `${headerComment(json, "Unity camera setup")}
using UnityEngine;

[ExecuteAlways]
public sealed class PlateCameraSetup : MonoBehaviour
{
    public Camera targetCamera;
    public Transform characterRoot;
    public Texture2D backgroundPlate;

    [Header("Generated camera")]
    public float verticalFovDeg = ${p.fieldOfViewDeg}f;
    public float aspect = ${p.aspect}f;
    public float nearClip = ${p.nearClipPlane}f;
    public float farClip = ${p.farClipPlane}f;
    public Vector3 position = new Vector3(${p.transform.position.x}f, ${p.transform.position.y}f, ${p.transform.position.z}f);
    public Vector3 eulerXYZ = new Vector3(${p.transform.eulerDegreesXYZ.x}f, ${p.transform.eulerDegreesXYZ.y}f, ${p.transform.eulerDegreesXYZ.z}f);

    void Reset()
    {
        targetCamera = GetComponent<Camera>();
    }

    void OnEnable()
    {
        Apply();
    }

    [ContextMenu("Apply generated plate camera")]
    public void Apply()
    {
        if (targetCamera == null) targetCamera = GetComponent<Camera>();
        if (targetCamera == null) return;

        targetCamera.fieldOfView = verticalFovDeg;
        targetCamera.aspect = aspect;
        targetCamera.nearClipPlane = nearClip;
        targetCamera.farClipPlane = farClip;
        targetCamera.transform.position = position;
        targetCamera.transform.rotation = Quaternion.Euler(eulerXYZ);
    }

    /* Normalized occluder polygons from the plate image.
       Convert each point {x,y} to plate UVs. Use them to build foreground matte meshes,
       sprite masks, or transparent depth-only meshes in front of the character.
${indentBlock(masks, "       ")}
    */
}`;
}

function blenderSnippet(json, p) {
  const cam = p.camera;
  const loc = p.objectTransform.locationXYZ;
  const rot = p.objectTransform.rotationEulerXYZRadians;
  return `# Blender camera setup
# Capture id: ${json.id}
# Plate image: ${json.image?.fileName || "unknown"}
# Run in Blender's Python console or as a Text script. Adjust image path as needed.
import bpy
import math
from pathlib import Path

plate_path = Path("${json.image?.fileName || "plate.jpg"}")
cam_data = bpy.data.cameras.new("PlateCamera_${safeFileName(json.id)}")
cam_data.type = "PERSP"
cam_data.lens_unit = "FOV"
cam_data.angle_y = ${cam.angleYRad}
cam_data.clip_start = ${cam.clipStart}
cam_data.clip_end = ${cam.clipEnd}
cam_obj = bpy.data.objects.new("PlateCamera_${safeFileName(json.id)}", cam_data)
bpy.context.collection.objects.link(cam_obj)
cam_obj.location = (${loc[0]}, ${loc[1]}, ${loc[2]})
cam_obj.rotation_euler = (${rot[0]}, ${rot[1]}, ${rot[2]})
bpy.context.scene.camera = cam_obj

# Optional: add the image as a camera background plate.
if plate_path.exists():
    bg = cam_data.background_images.new()
    bg.image = bpy.data.images.load(str(plate_path.resolve()))
    bg.frame_method = 'FIT'
    bg.alpha = 1.0

# Occluder polygons are in normalized image coordinates inside the JSON manifest.
# Build depth matte meshes manually from those polygons after setting your scene scale.`;
}

function threeSnippet(json, p) {
  return `${headerComment(json, "Three.js camera setup")}
import * as THREE from "three";

const camera = new THREE.PerspectiveCamera(
  ${p.constructor.fov},
  ${p.constructor.aspect},
  ${p.constructor.near},
  ${p.constructor.far}
);
camera.position.set(${p.position.x}, ${p.position.y}, ${p.position.z});
camera.rotation.order = "${p.rotationOrder}";
camera.rotation.set(${p.rotationRadians.x}, ${p.rotationRadians.y}, ${p.rotationRadians.z});
camera.updateProjectionMatrix();

// Put ${json.image?.fileName || "the plate image"} behind your WebGL canvas as a CSS background,
// or map it onto a plane at the exported backgroundDepthMeters.
const occluderPolygons = ${JSON.stringify(json.scene?.occluders || [], null, 2)};
`;
}

function godotSnippet(json, p) {
  return `# Godot 4 Camera3D setup
# Capture id: ${json.id}
# Plate image: ${json.image?.fileName || "unknown"}
extends Camera3D

func _ready() -> void:
    fov = ${p.Camera3D.fov}
    near = ${p.Camera3D.near}
    far = ${p.Camera3D.far}
    keep_aspect = Camera3D.KEEP_HEIGHT
    global_position = Vector3(${p.transform.origin.x}, ${p.transform.origin.y}, ${p.transform.origin.z})
    rotation_degrees = Vector3(${p.transform.rotationDegreesXYZ.x}, ${p.transform.rotationDegreesXYZ.y}, ${p.transform.rotationDegreesXYZ.z})

# Use a Sprite3D, Viewport background, or environment quad for the plate.
# Normalized occluder polygons from JSON can become foreground mask meshes.`;
}

function indentBlock(text, prefix) {
  return String(text).split("\n").map(line => prefix + line).join("\n");
}

export function makeMaskSvg(record) {
  const json = makeJsonForExport(record);
  const width = json.image?.width || 1;
  const height = json.image?.height || 1;
  const masks = json.scene?.occluders || [];
  const polygons = masks.map(mask => {
    const points = (mask.points || [])
      .map(pt => `${round(pt.x * width, 3)},${round(pt.y * height, 3)}`)
      .join(" ");
    return `<polygon id="${escapeXml(mask.id || "occluder")}" points="${points}" fill="white" />`;
  }).join("\n  ");
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <rect width="100%" height="100%" fill="black" />
  ${polygons}
</svg>
`;
}

export async function makeMaskPng(record) {
  const json = makeJsonForExport(record);
  const width = json.image?.width || 1;
  const height = json.image?.height || 1;
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  ctx.fillStyle = "black";
  ctx.fillRect(0, 0, width, height);
  ctx.fillStyle = "white";
  for (const mask of json.scene?.occluders || []) {
    const points = mask.points || [];
    if (points.length < 3) continue;
    ctx.beginPath();
    points.forEach((pt, i) => {
      const x = pt.x * width;
      const y = pt.y * height;
      if (i === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    });
    ctx.closePath();
    ctx.fill();
  }
  return new Promise(resolve => canvas.toBlob(resolve, "image/png"));
}

export async function buildCaptureZip(record) {
  const json = makeJsonForExport(record);
  const base = safeFileName(json.id || "capture");
  const zip = new JSZip();
  await addCaptureToZip(zip, record, base);
  return zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
}

export async function buildAllZip(records) {
  const zip = new JSZip();
  for (const record of records) {
    const json = makeJsonForExport(record);
    const base = safeFileName(json.id || "capture");
    await addCaptureToZip(zip, record, base);
  }
  zip.file("README.txt", allZipReadme(records));
  return zip.generateAsync({ type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } });
}

async function addCaptureToZip(zip, record, folderName) {
  const json = makeJsonForExport(record);
  const folder = zip.folder(folderName);
  const imageFile = json.image?.fileName || `${folderName}.${extensionFromMime(record.imageBlob?.type)}`;
  folder.file(imageFile, record.imageBlob);
  if (record.thumbnailBlob) folder.file(`thumb_${imageFile.replace(/\.[^.]+$/, ".jpg")}`, record.thumbnailBlob);
  folder.file(`${folderName}.json`, JSON.stringify(json, null, 2));
  folder.file("README.txt", captureReadme(json));

  const engines = folder.folder("engines");
  engines.file("generic_camera_manifest.json", generateEngineSnippet(record, "generic"));
  engines.file("unity_plate_camera.cs", generateEngineSnippet(record, "unity"));
  engines.file("unreal_camera.json", generateEngineSnippet(record, "unreal"));
  engines.file("blender_plate_camera.py", generateEngineSnippet(record, "blender"));
  engines.file("three_plate_camera.js", generateEngineSnippet(record, "three"));
  engines.file("godot_plate_camera.gd", generateEngineSnippet(record, "godot"));
  engines.file("gltf_camera.json", generateEngineSnippet(record, "gltf"));

  const masks = folder.folder("masks");
  masks.file("occluders.svg", makeMaskSvg(record));
  const maskPng = await makeMaskPng(record);
  if (maskPng) masks.file("occluder_mask.png", maskPng);
}

function captureReadme(json) {
  const cam = deriveCameraFromCapture(json);
  return `Phone Scene Calibrator capture

Capture id: ${json.id}
Created: ${json.createdAt}
Plate image: ${json.image?.fileName}
Image size: ${json.image?.width} x ${json.image?.height}
Vertical FOV: ${cam.lens.verticalFovDeg} deg
Horizontal FOV: ${cam.lens.horizontalFovDeg} deg
Camera height: ${cam.transformMeters.position.y} m
Pitch down: ${cam.transformMeters.rotationEulerDeg.pitchDownX} deg

Important limits:
- Browser camera APIs usually do not expose calibrated focal length, lens distortion, rolling shutter, or true depth.
- Use the JSON values as a starting point, then calibrate with known scene measurements and occlusion masks.
- The masks folder contains foreground occluder data drawn in the app.
`;
}

function allZipReadme(records) {
  return `Phone Scene Calibrator export

Captures: ${records.length}
Each capture folder contains:
- plate image
- paired JSON manifest
- engine snippets/manifests
- foreground occluder masks as SVG/PNG

Import the plate image as a fixed background, create a camera using the exported FOV/aspect/pose, and use the masks as foreground matte/depth-only occluders.
`;
}

function escapeXml(input) {
  return String(input)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}
